version: '3'

services:
  insplus:
    build:
      context: .
    image: ins-img:latest
    container_name: insplus
    restart: always
    ports:
      - '80:80'
    volumes:
      - ../biz_insplus:/var/www/html